### ISSUE TITLE
no stackable shulker boxes?

### ISSUE THREAD

**Issue by pirc12334** [maruohon/tweakeroo#104]
Im playing in 1.12.2 and as ive seen i should have an option to stack empty shulker boxes.

**Comment by maruohon** [comment]
The stackable shulker boxes option in Tweakeroo only works if you are playing in single player, as that code needs to run on the server side, which in a client mod is only possible in the integrated server case, ie. when playing single player.

But yes the option does exist. But since you are playing on 1.12.2, are you using the super old 0.9.x version from CurseForge? I don't remember if that version had that feature yet, but in any case you shouldn't use that old version anyway. The latest 1.12.2 builds are currently only on my server here: https://masa.dy.fi/mcmods/client_mods/ So get all of the mods for 1.12.2 (that you use of those) from there for now. I'll probably upload all of them to CurseForge again after I finish the current refactors and changes and do the next round of updates, before starting to port all that new code to 1.13.2+ again as well.

**Comment by pirc12334** [comment]
i am using this version from your site. runing the liteloader one. how would i enable the feature?

**Comment by maruohon** [comment]
In the Tweak Toggles category, enable the `tweakEmptyShulkerBoxesStackOnGround` option (assuming you only want them to stack when thrown on the ground, like in the Carpet mod).

**Comment by pirc12334** [comment]
ok im sorry i thought i was opening tweakeroos menu but i was opening litematicas menu. Thank you for helping.
