### ISSUE TITLE
X+C crashes the game

### ISSUE THREAD

**Issue by L-Lawlite** [maruohon/tweakeroo#113]
In 20w45a snapshot of minecraft 1.17 java X+C crashes the game

**Comment by maruohon** [comment]
Thanks for no information >\_>

Using the snapshot version, or the 1.16.4 version? The 1.16.x versions will not work on the snapshots. What is the crash log?

The snapshot versions are available here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.17+snapshot+%26+pre

There most likely will not be versions for all snapshots, because wasting time chasing Mojang's changes every week is not good use of my time. That's also why there is no Litematica yet, as it would need more work porting it fully (I did the easy changes), which I don't feel like doing since it will likely break countless times before 1.17 anyway.
