### ISSUE TITLE
TweakSwapAlmostBrokenTools doesnt work

### ISSUE THREAD

**Issue by SouthernPixel** [maruohon/tweakeroo#137]
TweakSwapAlmostBrokenTools is suppose to swap to another tool when the current one is about to break like it says but it doesnt and only says its about to break, yes i have it on so I am not sure why it's not working

**Comment by maruohon** [comment]
More context? Which MC version? Which item/tool were you using?  You said you got the message, but the item didn't get switched? Was your inventory completely filled with other tools?

**Comment by SouthernPixel** [comment]
Why is context needed, i explained it in the question and from what i put in the question should be enough info to go off of. I am using a pickaxe to mine and when it is about to break it doesnt switch to a pickaxe that is in my inventory. I have a fresh pixkaxe in my inventory and empty slots as well. I am using Baritone on 1.16.3

**Comment by maruohon** [comment]
> what I put in the question should be enough info to go off of

Oh really? Did you think about that for a second? The mod exists currently for 6 different MC versions, on 4 different mod loaders. You didn't specify in your first message ANY information beyond "it doesn't work". No MC version, no mod version, not what items/tools you were actually using, whether your inventory was completely filled with tools or with other items, which affects the behavior of how the tool swap tweak works. And when I go in a test world it works fine.

Okay and *now* you tell me you are even using Baritone. That is a fairly significant detail you know? Because it changes entirely how the item is used in the code. My first guess is now that it's because of Baritone, since it works fine for me in a test world. Did you try it while mining manually, without Baritone?

**Comment by SouthernPixel** [comment]
*sigh* sorry about that, i was asking somebody else a question on another github page and they really annoyed me because they kept closing the qeustion before the qeustion was resolved. Sorry i was just pissed off :/
Well i tried using it with and without #sel cleararea and it still only says its about to break and not switches to my other fresh pickaxe that i have in my inventory (not my hotbar) it does easily fill my inventory with blocks while I mine, is that why its not switching? I mean shouldnt it swap the almost broken pickaxe with the fresh pickaxe in the slot the fresh pickaxe is in? lol idk why i brought up baritone i forgot this is about tweakaroo not that. Yes i tried with and without baritone mining

**Comment by maruohon** [comment]
It should always switch the about-to-break item *somehow*. So if there is another item of the same type with durability left, it should switch to that. If there isn't a replacement, it should move the tool away from the selected hotbar slot, into an empty slot, or if there are no empty slots left, then it tries to find a non-damageable item to swap to the hand, such as stone.

All I can say is that the swapping works in my test world, and I know lots of people why are using it. So my best guess is that it's either some kind of conflict with another mod, but that seems somewhat unlikely if you still get the message. Or it could be caused by server <-> client de-sync or sync delay.

Do you get the message multiple times, for as long as the item finally breaks? Or how exactly does it behave? I'm not at all familiar with how Baritone works or is installed, so I can't say anything about that. Did you try completely without Baritone installed? Does the server run Spigot/Paper? Those might also limit some packets from the client if they happen too quickly, not sure if that would affect this swapping.

**Comment by SouthernPixel** [comment]
The server doesnt really run on anything its just a manually created server, im not entirely sure tbh. We do run fabric though if that helps. Yea i tried with and without Baritone and it still only tells me not actually swaps. Oh and it only says the message once and not again until the tool is almost broken again.

**Comment by SouthernPixel** [comment]
Ok now its not even telling me the message https://imgur.com/a/qytphbz

**Comment by SouthernPixel** [comment]
Ok apparently it was because of Baritone. apparently making Baritone mine for me doesnt consider it as an input that it can swap with and I needed to update Tweakaroo
