### ISSUE TITLE
Flexible block placement doesn't work for some blocks

### ISSUE THREAD

**Issue by JASMein03M** [maruohon/tweakeroo#154]
I have installed carpet and carpet extra on my server but for some reason the face into a block option won't work for some blocks. For example, it does work for observers but doesn't for pistons. I don't know if this is a bug or that it is something that I did wrong.

**Comment by maruohon** [comment]
Did you read the section about block rotations on the CurseForge page, and followed all the advice? From default settings, you need to enable the `carpetAccuratePlacementProtocol` option in Tweakeroo (currently at the top of Tweak Toggles), and the `accurateBlockPlacement` rule in CarpetExtra on the server: `/carpet accurateBlockPlacement true` and `/carpet setDefault accurateBlockPlacement true`. Then enable the Accurate Block Placement tweak and set the into and reverse keys that you use to control how to place the blocks.

If one of pistons or observers is working, then the other should work as well. Note that observers are defined kind of backwards in vanilla to what many people would think.

**Comment by JASMein03M** [comment]
Yes, I did all that. Here is a video of me trying to face a piston into a block.
https://user-images.githubusercontent.com/77641028/105073266-1f786200-5a87-11eb-92b2-f379ec8b66c8.mp4

**Comment by maruohon** [comment]
Ah so it is actually working. But you are using the Flexible Block Placement's center region for trying to face into a block. That is actually not defined as "face into", but instead I think it's "opposite from normal" while the initial facing is the clicked block face. And since the normal facing and the direction for pistons is defined the way it is, in that example it just doesn't seem to do anything for pistons.

So basically for piston, observer and dropper/dispenser rotations you would usually want to use the Accurate Block Placement feature instead of Flexible Block Placement. It's more suitable as it defines proper "into" and "reverse" (from what it would be otherwise with other current rotation requests, if any) actions. Flexible is only really useful for rotations if you need to rotate something "sideways" ie. not facing either into or directly away from the block you place against.

**Comment by JASMein03M** [comment]
O, I did not know that. Thank you for the information! And thank you for this wonderful mod!
