### ISSUE TITLE
Without freecam

### ISSUE THREAD

**Issue by randomairborne** [maruohon/tweakeroo#217]
Would it be possible to recompile this mod without freecam, so it can be used on servers that consider freecam a hack?

**Comment by ghost** [comment]
Why can’t u just not use the feature? The whole point of the mod is that everything is up to the user.

**Comment by maruohon** [comment]
> Would it be possible to recompile this mod without freecam

Of course it's *possible* to remove any feature you want. And you can do that for yourself if you want. But I'm not going to make and maintain random versions of the mod with random features disabled. It's a ton of maintenance overhead, and would also be confusing for both the users and me if they report that something doesn't work or exist, if they somehow accidentally find and install the "wrong" version of the mod.

And quite literally nobody agrees what features are too cheaty for them anyway. If we take as an example the latest 1.16.4 build, it has 32 "disable features" and 74 "tweaks". If we assume nobody agrees on what is too cheaty and there would need to be a different mod build for every possible combination of features with one or more features disabled, that would mean there would currently need to be `2^(74 + 32)  = 2^106 = 81129638414606681695789005144064` different versions of the mod. (Okay this is a bit of an extremified example, but still demonstrates the point...)

The upcoming big updates of the mods will allow the server to request features to be disabled, so that should be a an all-around better solution to this anyway. The player does not even need to care or know about what features are disallowed on a server, as they would be automatically disabled and the toggle configs would have a message stating that the server has disabled that feature.

**Comment by UltraBlackLinux** [comment]
@maruohon 
Frankly, I wouldn't want a serverside toggle lol
Freecam is a wonderful tool, that lets you look behind the scenes and lets you circumvent annoying stuff. 
I don't like limitations, like these
:/

**Comment by maruohon** [comment]
@UltraBlackLinux I have also seen it used by a lot of builders just to get a quick look from the "outside" or small distance away. And it's also very handy for looking at mob farms running while you AFK ~100 block away yourself, or to look at tightly packed redstone contraptions (which was mostly the original reason for adding it). Unfortunately just due to the nature of the tweak it can also be used for pretty blatant cheating, ie. for example finding stuff underground.

There is no way to please everyone with features and issues like this. Many people have requested ways to remove or disable a number of different features from my mods, in some cases simply because the server they play on does not allow the mod at all without being able to disable some features. So a way for the server to request things to be disabled will be added. However I'm not entirely sure if I will also add a (possibly hidden) way to disable/bypass that system, simply to avoid a number of altered "cracked" unofficial versions of the mods to pop up simply to remove that bypass. No system like that done on the client side would ever actually be secure anyway.

The feature locking system would be partially intended for servers where the players follow the rules anyway, and automatically disabling the features would be more of a convenience for the player, as they wouldn't have to keep track of which features exactly are allowed, and remembering not to use them, as they would be automatically disabled. This in particular has also been requested.

**Comment by randomairborne** [comment]
if it is possible, then i will do it for myself, i was just wondering the actual possibility, as if maybe something depended on it.

**Comment by randomairborne** [comment]
> 
> 
> Why can’t u just not use the feature? The whole point of the mod is that everything is up to the user.

I asked about this. Provided the mod has freecam at all. it is not allowed.
