### ISSUE TITLE
litematica compatibility

### ISSUE THREAD

**Issue by ProkopRandacek** [maruohon/tweakeroo#27]
The pick before place tweak does ignores litematica ghost block pickinig.

**Comment by vacla** [comment]
this is not from tweakeroo, that is a tweak from litematica. There is also pick after tweak in litematica.

**Comment by maruohon** [comment]
Yep, it's not possible for Tweakeroo to know anything about Litematica currently. I would have to add a proper API for it to hook into.

But more to the point, the built-in pick block features in Litematica should already cover this use case. Specifically the `pickBlockLast` hotkey, if you set that to the vanilla use key (usually right click), and then set the advanced keybind setting to **not** cancel further processing, then it would always do an automatic pick block just before placing a block.

However it only happens when you right click, not when you just hold down the right click button... For that I still need to add some better way for the pick block to work. Probably just check for the `pickBlockLast` being held down when the use packet is about to be sent, and then do the pick block there.
