### ISSUE TITLE
After clicker isn't working for me...

### ISSUE THREAD

**Issue by TestSubjectLizzy** [maruohon/tweakeroo#332]
The title says it all, I'm on default after clicker settings and no other tweaks enabled and it just dosent work, I place a repeater and it stays on one tick

**Comment by maruohon** [comment]
In most cases you need to disable the Generic -> `carpetAccuratePlacementProtocol` option while you use the After Clicker, as otherwise it will try to just add some properties via the protocol (and I think it only does anything for Repeaters in that case?). And if the server does not have Carpet mod (and CarpetExtra) with the `accurateBlockPlacement` rule enabled, then it won't do anything.

I probably need to add a new option that controls if the After Clicker should try to use the protocol or not, and have that option be disabled by default, that way it will by default actually do normal extra clicks on the block.

**Comment by TestSubjectLizzy** [comment]
ok thanks for letting me know, I did have the rule enabled so I will test when I get back on tommorow. maybe add a rule that auto disables the carpetAccurateBlockPlacementProtocol the same way the one rule enables the placement limiter when you enable fast place
