### ISSUE TITLE
Ghost blocks with Accurate Block Placement

### ISSUE THREAD

**Issue by DemonSlayer112** [maruohon/tweakeroo#344]
![image](https://user-images.githubusercontent.com/70122500/165257712-278e3bc0-2bc4-4d72-b331-be7c9fd7b3b8.png)
![image](https://user-images.githubusercontent.com/70122500/165257775-43f395c0-9e77-4d31-9ef8-a7d71c2ba98b.png)
I havent changed very much of the default of the mod.
Other than freecam to backspace hotkey.

When you place a piston using z/x if you click the piston after with another block it will void it with the block you clicked.
The piston also doesnt seem to extend when powered, this feels like a ghost block.
Weirdly enough other blocks dont do this.

tweakeroo-fabric-1.18.2-0.13.1.jar

**Comment by maruohon** [comment]
This is caused by an added check in vanilla in 1.18.2. See here for the longer explanation: https://github.com/maruohon/litematica/issues/521

Are you in single player or on a server? If you are on a server, then the server would need CarpetExtra `1.4.69` or later and the `accurateBlockPlacement` rule enabled to have the fix/bypass, otherwise any item use packets from the client that include data in the "accurate placement protocol" will be rejected by the server and will remain client-side ghost blocks.

**Comment by maruohon** [comment]
I just uploaded Litematica 0.11.3 and Tweakeroo 0.13.3, which separate that fix/bypass to a new option that is not tied to any actual feature being enabled in the mods.
