### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by Yoad1704** [maruohon/tweakeroo#352]
Hi, I've been using this mod for a while and now when 1.19 is out I want to use it there as well. Any chance to update it soon?

**Comment by maruohon** [comment]
Please don't spam the same issue to all the mod repos... that doesn't accomplish anything. I know about 1.19 being out. I've been busy IRL and haven't had time to do any modding in a number of weeks. There is much to do for the 1.19 ports because I want to make them based on the newer development code from 1.12.2. So no ETAs.

**Comment by Yoad1704** [comment]
k, sry didn't know about it

**Comment by magnus-ISU** [comment]
For anyone else, there are versions here already existing ported by kosma. https://kosma.pl/masamods/
