### ISSUE TITLE
Fastleftclick and Fastrightclick not working

### ISSUE THREAD

**Issue by cardboardthings** [maruohon/tweakeroo#479]
the fastclicking is on but its not working help pls
https://youtu.be/ZYpkhj7e0ro

**Comment by maruohon** [comment]
There are some other mods that conflict with most of the clicking and block placing features of Tweakeroo. I don't remember for sure but either Item Swapper or Inventory Profiles Next might be one of them. Do you have some inventory or clicking related other mods?

**Comment by cardboardthings** [comment]
what mod does it have conflict with?
https://youtu.be/ft3kcNLEua4

**Comment by maruohon** [comment]
I don't know, there have been a few different mods.

You can first try if it works with your current settings if you just leave malilib and Tweakeroo active. Or one mod that might be related is Click Through. I think there was a conflict with one mod that allows clicking through tall grass, but I think it was called something like Clear View (I can't remember for sure)?

If it's not that then to quickly narrow it down you'd probably have to remove half of the mods at a time and see which half has the conflicting mod, and continue that until you find the one. That way you only need to do it a few times instead of a hundred times or however many mods you have.

**Comment by cardboardthings** [comment]
found it because of baritone thanksssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
