### ISSUE TITLE
[Fabric 1.20.1] AccurateBlockPlacement works on server, but not on singleplayer

### ISSUE THREAD

**Issue by FenixC4** [maruohon/tweakeroo#482]
### Mods

- appleskin
- architectury
- cardinal-components
- carpet-extra
- cc:bridge
- cloth-config
- clumps
- create additions
- create sodium fix
- easier chests
- extended drawers
- fabric api
- fabric carpet
- fabric language kotlin
- falling tree
- indium
- inventory hud plus
- iris
- jade
- lamb dynamic lights
- litematica
- lithium
- malilib
- minihud
- modmenu
- observable
- offlineskins
- REI
- sodium
- sound physics remastered
- steam and rails for create
- tom's storage
- traveler's backpack
- tweakeroo
- twitchchat
- xaero's minimap & worldmap

The title explains preety much all. I had problems with tweakeroo's accurate placement where in creative the block would just dissapear and in survival it would leave ghost blocks. I followed every advices i could find on github on that, and none of them worked. Finally i deciced to just host a fabric server and load all the mods and configs from my singleplayer to the server. And upon entering the world and enabling the protocol in carpet (which i also did on singleplayer) it works flawlessly. Could this be a bug or it just works like that. Or maybe some of the mods like indium and sodium and whatnot are causing this strange behaviour ?

**Comment by maruohon** [comment]
If it only doesn't work while in single player, then that means that something is not handling the accurate placement on the server thread, or more precisely is not bypassing the vanilla item use check added in 1.18.2. Since you also have Litematica installed, check that you haven't disabled the Litematica config Generic -> `itemUsePacketCheckBypass`. That is related to the bypass of the vanilla check added in1.18.2, without which any attempt to use the carpet "accurate placement protocol" will result in ghost blocks and failed placement.

Another option that might be related is Generic -> `easyPlaceSinglePlayerHandling`, but that should not cause the placement to fail entirely. Basically you want both of those configs at their default values, and also Tweakeroo's Generic -> `clientPlacementRotation` should be enabled. And then preferably you would disable Carpet's `accurateBlockPlacement` in single player, and let Litematica and/or Tweakeroo handle it.

**Comment by FenixC4** [comment]
Ohh it all works now. No idea why i had `itemUsePacketCheckBypass` turned of since i didn't touch any of these but it all works now
