### ISSUE TITLE
Zoom is missing or broken in 0.9.4

### ISSUE THREAD

**Issue by el0c** [maruohon/tweakeroo#5]
The Zoom tweak is absent from Tweakeroo in the 0.9.4 updates.
The patch notes listed as just an update to 1.14.2; so I assume this was an accidental retrogression from when the patch notes said it got cherry picked in 0.9.2 where it was usable, as well as 0.9.3.
Or was there an issue with the tweak that need it to be disabled?

**Comment by maruohon** [comment]
I kind of purposefully left it out, as I didn't include that commit in the main fabric branch, but I kept it in a separate branch and had to cherry-pick it again after each update on the main branch (could have merged the main too I guess... but we), because it will be pulled in by the 0.10.0 merge later on. But it seems quite a few people were using it, so I'll probably include it back in the next point release until the actual 0.10.0 release happens.
