### ISSUE TITLE
please add 1.21

### ISSUE THREAD

**Issue by NikeyV1** [maruohon/tweakeroo#510]

**Comment by NikeyV1** [comment]
Yes pls

**Comment by Samalando** [comment]
Masa has stated that he will not continue to update past 1.20.5 due to minor versions getting mod-breaking changes and he also has burnout. You can get 1.21 from [sakura ryokos github](https://github.com/sakura-ryoko), and that will be where the mods will get updated until further notice. I do think that it is on curseforge though.

**Comment by Samalando** [comment]
Masa has stated that he will not continue to update past 1.20.5 due to minor versions getting mod-breaking changes and he also has burnout. You can get 1.21 from [sakura ryokos github](https://github.com/sakura-ryoko), and that will be where the mods will get updated until further notice. I do think that it is on curseforge though.

**Comment by Samalando** [comment]
I accidentally double posted
