### ISSUE TITLE
disableBlockBreakCooldown does not work in creative mode

### ISSUE THREAD

**Issue by MacroVoid** [maruohon/tweakeroo#534]
disableBlockBreakCooldown does not work only in creative mode.
Fabric version: **0.16.9**
Minecraft version: **1.21.1**
Tweakeroo version: **1.21.1-0.21.54**
Log: https://gist.github.com/MacroVoid/8fa299d976d4421a8a8c1728108a47c1

https://github.com/user-attachments/assets/5afb379f-e327-4c77-8f52-2ffa05a01477

**Comment by sakura-ryoko** [comment]
This was an intentional change to block it from being used in Creative because players complained it was " too fast " and caused problems.

**Comment by MacroVoid** [comment]
OK, but is it possible to add a setting that will turn it on in creative mode or a slider to adjust cooldown?

**Comment by maruohon** [comment]
Traditionally in creative mode you would just use `tweakFastLeftClick` to break stuff fast.

**Comment by MacroVoid** [comment]
> Traditionally in creative mode you would just use `tweakFastLeftClick` to break stuff fast.

1) Why use two different functions for the same action?
2) `tweakFastLeftClick` does not just remove cooldown when digging, but removes cooldown when clicking the mouse, and because of this, in small rooms you can hit a mob that does not need to be beaten, which does not happen when using `disableBlockBreakCooldown`

https://github.com/user-attachments/assets/29cde74d-07d7-4e26-baf8-94c3f615f075

In the video, I used the "No Mining Cooldown" mod, which works in creative mode, but I really want tweakeroo to have this feature available.
P.S. when pointing at blocks and villagers, the LMB was clamped

**Comment by maruohon** [comment]
Well I said "traditionally" because for several years there was no mining cooldown tweak at all. And back then lots of people used the fast left click tweak for breaking blocks in creative mode. Or at least I did... and I know *some* other people did too.

But yes I agree that it would be better for the no mining cooldown tweak to also work in creative mode. If/when people don't want that in creative mode, then just toggle off the tweak, like you do with every other feature in the mod whenever you do or don't want to use something.

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-0.21.55-sakura.3
reverts this.

**Comment by MacroVoid** [comment]
Thanks!
